<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>s</string>
		<string>$C</string>
	</array>
	<key>name</key>
	<string>lh5801 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ORIGIN|FRAGMENTS|BASIC|CODE|BYTE|WORD|LONG|TEXT|KEYWORD|VAR|XREG|RESERVE|HOLE|LENGTH|STRINGIFY)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Z|NZ|C|NC|z|nz|c|nc)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.asm.lh5801</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.asm.lh5801</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.include.asm.lh5801</string>
		</dict>
		<dict>
			<key>match</key>			
			<string>\b(ADC|ADD|AND|AEX|ATP|AM0|AM1|BIT|CALL|CDV|CLA|CPA|CPI|CP|DADC|DEC|DI|DJC|DSBC|EI|HALT|INC|INA|JR|LDA|LDD|LDI|LD|NOP|OR|OFF|POP|PUSH|RCF|RDP|RET|RL|RR|RLD|RRD|RPU|RPV|RTI|SBC|SBR|SCF|SDP|SL|SR|SPU|SPV|STA|STD|STI|XOR|LDW|LJNE|JNE|BKW|LJNES|STS|LDS|VAR|INTG|ARG|STB|LDB|IFC|STVP|LDPT|EVAL|ERRH|RST|ERR1|LYX|NORM|SLX|CLX|ADN|SXY|CLS|LDU|STU|OUTA|RSET|STA|STI|SWA|SWP|SLD|SRD)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.asm.lh5801</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\d{5}</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b-?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[#$%]-?(0x)?[0-9a-fA-F]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(A|B|C|D|E|F|H|L|I|R|IX|IY|AF|BC|DE|HL|PC|SP|AF'|Z|a|b|c|d|e|f|h|l|i|r|ix|iy|af|bc|de|hl|pc|sp|af'|z|HLI|hli|HLD|hld)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>		
	</array>
	<key>scopeName</key>
	<string>source.asm.lh5801</string>
	<key>uuid</key>
	<string>5075ff92-54a7-11e6-beb8-9e71128cae77</string>
</dict>
</plist>
